services:
  # Экземпляр PRODUCTION (Порт 8001)
  app_production:
    build: 
      context: .
    platform: linux/amd64
    container_name: zmk_production
    restart: always
    ports:
      - "8001:3000"
    environment:
      - NODE_ENV=production
      - APP_TYPE=production
      - DATABASE_URL=postgresql://aleksandr:password@host.docker.internal:5432/zmk_production
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./logs/production:/app/logs
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1G

  # Экземпляр SUPPLY (Порт 8002)
  app_supply:
    build:
      context: .
    platform: linux/amd64
    container_name: zmk_supply
    restart: always
    ports:
      - "8002:3000"
    environment:
      - NODE_ENV=production
      - APP_TYPE=supply
      - DATABASE_URL=postgresql://aleksandr:password@host.docker.internal:5432/zmk_supply
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./logs/supply:/app/logs
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1G

  # Portainer (Графическая панель)
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data:
